services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.13-bookworm
    container_name: som-energia-dev
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:homeassistant

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.12.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../custom_components/som_energia:/config/custom_components/som_energia:ro
      - /config
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true